"""initial schema 11 tables

Revision ID: 57a9c8a6171c
Revises: 
Create Date: 2026-09-03 02:00:22.461011

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '57a9c8a6171c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id_category', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('display_order', sa.SmallInteger(), server_default=sa.text('0'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id_category'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('clients',
    sa.Column('id_client', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('document_identification', sa.String(length=30), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('phone1', sa.String(length=20), nullable=False),
    sa.Column('phone2', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id_client'),
    sa.UniqueConstraint('document_identification'),
    sa.UniqueConstraint('email')
    )
    op.create_table('sessions',
    sa.Column('id_session', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=False),
    sa.Column('creation_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_activity_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id_session')
    )
    op.create_table('states',
    sa.Column('id_state', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id_state'),
    sa.UniqueConstraint('name')
    )
    op.create_table('carts',
    sa.Column('id_cart', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('id_session', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('status', sa.Enum('active', 'abandoned', 'converted', name='ck_carts_status', native_enum=False, create_constraint=True, length=20), server_default='active', nullable=False),
    sa.ForeignKeyConstraint(['id_session'], ['sessions.id_session'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_cart'),
    sa.UniqueConstraint('id_session')
    )
    op.create_table('products',
    sa.Column('id_product', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('id_category', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('slug', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('price_type', sa.Enum('fixed', 'starting_from', name='ck_products_price_type', native_enum=False, create_constraint=True, length=20), server_default='fixed', nullable=False),
    sa.Column('is_featured', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.CheckConstraint('price >= 0', name='ck_products_price_non_negative'),
    sa.ForeignKeyConstraint(['id_category'], ['categories.id_category'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id_product'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('orders',
    sa.Column('id_order', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('id_cart', sa.UUID(), nullable=True),
    sa.Column('id_client', sa.UUID(), nullable=False),
    sa.Column('id_state', sa.UUID(), nullable=False),
    sa.Column('delivery_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reference_image', sa.Text(), nullable=True),
    sa.Column('event_type', sa.String(length=100), nullable=True),
    sa.Column('guest_count', sa.Integer(), nullable=True),
    sa.Column('description_order', sa.Text(), nullable=True),
    sa.Column('quoted_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('delivery_address', sa.String(length=255), nullable=True),
    sa.Column('shipping_cost', sa.Numeric(precision=10, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=10, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('total', sa.Numeric(precision=10, scale=2), server_default=sa.text('0'), nullable=False),
    sa.CheckConstraint('guest_count >= 0', name='ck_orders_guest_count_non_negative'),
    sa.CheckConstraint('quoted_price >= 0', name='ck_orders_quoted_price_non_negative'),
    sa.CheckConstraint('shipping_cost >= 0', name='ck_orders_shipping_cost_non_negative'),
    sa.CheckConstraint('subtotal >= 0', name='ck_orders_subtotal_non_negative'),
    sa.CheckConstraint('total >= 0', name='ck_orders_total_non_negative'),
    sa.ForeignKeyConstraint(['id_cart'], ['carts.id_cart'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['id_client'], ['clients.id_client'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['id_state'], ['states.id_state'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id_order'),
    sa.UniqueConstraint('id_cart')
    )
    op.create_index(op.f('ix_orders_id_client'), 'orders', ['id_client'], unique=False)
    op.create_index(op.f('ix_orders_id_state'), 'orders', ['id_state'], unique=False)
    op.create_table('product_cart',
    sa.Column('id_cart', sa.UUID(), nullable=False),
    sa.Column('id_product', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('item_subtotal', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('special_instructions', sa.Text(), nullable=True),
    sa.CheckConstraint('item_subtotal >= 0', name='ck_product_cart_item_subtotal_non_negative'),
    sa.CheckConstraint('quantity > 0', name='ck_product_cart_quantity_positive'),
    sa.CheckConstraint('unit_price >= 0', name='ck_product_cart_unit_price_non_negative'),
    sa.ForeignKeyConstraint(['id_cart'], ['carts.id_cart'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_product'], ['products.id_product'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id_cart', 'id_product')
    )
    op.create_table('order_product',
    sa.Column('id_order', sa.UUID(), nullable=False),
    sa.Column('id_product', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('item_subtotal', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('special_instructions', sa.Text(), nullable=True),
    sa.CheckConstraint('item_subtotal >= 0', name='ck_order_product_item_subtotal_non_negative'),
    sa.CheckConstraint('quantity > 0', name='ck_order_product_quantity_positive'),
    sa.CheckConstraint('unit_price >= 0', name='ck_order_product_unit_price_non_negative'),
    sa.ForeignKeyConstraint(['id_order'], ['orders.id_order'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_product'], ['products.id_product'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id_order', 'id_product')
    )
    op.create_table('order_state_history',
    sa.Column('id_order_state_history', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('id_order', sa.UUID(), nullable=False),
    sa.Column('id_state', sa.UUID(), nullable=False),
    sa.Column('changed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['id_order'], ['orders.id_order'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id_state'], ['states.id_state'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id_order_state_history')
    )
    op.create_index(op.f('ix_order_state_history_id_order'), 'order_state_history', ['id_order'], unique=False)
    op.create_index(op.f('ix_order_state_history_id_state'), 'order_state_history', ['id_state'], unique=False)
    op.create_table('payments',
    sa.Column('id_payment', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('id_order', sa.UUID(), nullable=False),
    sa.Column('transaction_gateway_id', sa.String(length=255), nullable=True),
    sa.Column('gateway_status', sa.String(length=50), nullable=True),
    sa.Column('paid_method', sa.String(length=50), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.Enum('pending', 'completed', 'failed', 'refunded', name='ck_payments_status', native_enum=False, create_constraint=True, length=20), server_default='pending', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('amount >= 0', name='ck_payments_amount_non_negative'),
    sa.ForeignKeyConstraint(['id_order'], ['orders.id_order'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_payment')
    )
    op.create_index(op.f('ix_payments_id_order'), 'payments', ['id_order'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payments_id_order'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_order_state_history_id_state'), table_name='order_state_history')
    op.drop_index(op.f('ix_order_state_history_id_order'), table_name='order_state_history')
    op.drop_table('order_state_history')
    op.drop_table('order_product')
    op.drop_table('product_cart')
    op.drop_index(op.f('ix_orders_id_state'), table_name='orders')
    op.drop_index(op.f('ix_orders_id_client'), table_name='orders')
    op.drop_table('orders')
    op.drop_table('products')
    op.drop_table('carts')
    op.drop_table('states')
    op.drop_table('sessions')
    op.drop_table('clients')
    op.drop_table('categories')
    # ### end Alembic commands ###
