"""
Base model and shared column helpers for all entities.

Targets PostgreSQL: UUID primary keys are generated database-side with
gen_random_uuid() (native since PostgreSQL 13) and timestamps are TIMESTAMPTZ.
"""

import enum
import uuid
from datetime import datetime

from sqlalchemy import DateTime, Enum as SAEnum, text
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column


class Base(DeclarativeBase):
    """Base class for all ORM models."""
    pass


def enum_column(
    enum_cls: type[enum.Enum], constraint_name: str, length: int = 20
) -> SAEnum:
    """
    A VARCHAR column constrained by CHECK, matching the SQL schema's
    `status VARCHAR(20) CHECK (status IN (...))` style.

    Stores the enum's *values* ('active') rather than SQLAlchemy's default of
    member names ('ACTIVE'), and emits the CHECK constraint, which SQLAlchemy
    omits unless create_constraint is set.
    """
    return SAEnum(
        enum_cls,
        native_enum=False,
        create_constraint=True,
        name=constraint_name,
        length=length,
        values_callable=lambda cls: [member.value for member in cls],
    )


def uuid_pk() -> Mapped[uuid.UUID]:
    """
    Primary key column: UUID generated by PostgreSQL via gen_random_uuid().

    Mirrors `UUID PRIMARY KEY DEFAULT gen_random_uuid()` from the SQL schema.
    """
    return mapped_column(
        UUID(as_uuid=True),
        primary_key=True,
        server_default=text("gen_random_uuid()"),
    )


def created_at_column() -> Mapped[datetime]:
    """Standard `created_at TIMESTAMPTZ NOT NULL DEFAULT now()` column."""
    return mapped_column(
        DateTime(timezone=True),
        server_default=text("now()"),
        nullable=False,
    )


class TimestampMixin:
    """Mixin that adds created_at and updated_at timestamps."""

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=text("now()"),
        nullable=False,
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=text("now()"),
        onupdate=text("now()"),
        nullable=False,
    )
